# Generated by Django 3.0.3 on 2020-08-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conc_Number', models.CharField(max_length=26, unique=True)),
                ('Description', models.CharField(blank=True, max_length=260, null=True)),
                ('Drawing_issue', models.CharField(blank=True, max_length=2, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('DP', models.BooleanField(default=False)),
                ('Indate', models.DateField()),
                ('Outdate', models.DateField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('Decision', models.CharField(choices=[('Open', 'Open'), ('ACAT3', 'Accept CAT3'), ('ACAT2', 'Accept CAT2'), ('ACAT1', 'Accept CAT1'), ('ACATX', 'Accept CATX')], max_length=26, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Partnumber', models.CharField(max_length=26, unique=True)),
                ('Supplier', models.CharField(max_length=26)),
                ('Commodity', models.CharField(choices=[('Rotatives Fan', 'Rotatives Fan'), ('Rotatives Compressor', 'Rotatives Compressor'), ('Rotatives Shaft', 'Rotatives Shaft'), ('Rotatives Turbine', 'Rotatives Turbine')], max_length=26)),
                ('Engine', models.CharField(choices=[('Tay', 'Tay'), ('BR700', 'BR700'), ('BR710', 'BR710'), ('BR725', 'BR725'), ('BR700NG', 'BR700NG'), ('RB3043', 'RB3043')], max_length=26, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=26)),
                ('Description', models.CharField(blank=True, max_length=260, null=True)),
                ('SNumber', models.CharField(max_length=26)),
                ('Feature', models.CharField(choices=[('Curvic', 'Curvic'), ('Hole', 'Hole'), ('Entire part', 'Entire part'), ('rear wall', 'rear wall')], max_length=26)),
                ('Requirement', models.CharField(choices=[('Diameter', 'Diameter'), ('Length', 'Length'), ('Position', 'Position'), ('RQSC', 'RQSC')], max_length=26)),
                ('Mpos', models.CharField(blank=True, max_length=26)),
                ('Grid', models.CharField(blank=True, max_length=26)),
                ('Nom', models.CharField(blank=True, max_length=26)),
                ('Tol', models.CharField(blank=True, max_length=26)),
                ('Actual', models.CharField(blank=True, max_length=26)),
                ('Unit', models.CharField(choices=[('mm', 'mm'), ('degree', 'degree'), ('inch', 'inch')], max_length=26)),
                ('Rootcause', models.CharField(choices=[('Salvage', 'Salvage'), ('Process capability', 'Process capability'), ('Human error', 'Human error')], max_length=26)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedDate', models.DateTimeField(auto_now=True, null=True)),
                ('Conc_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concession.con')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='con',
            name='partnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concession.part'),
        ),
    ]
